server:
  port: 20050
  servlet:
    context-path: /file

spring:
  application:
    name: gb-easychat-filesystem-service
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: 1dd53a7f-c79f-4620-ad6e-fade5bac680d
        cluster-name: shanghai
        group: easychat

minio:
#  "http://localhost:9090"
  endpoint: "http://localhost:9000"
  accessKey: "minioadmin"
  secretKey: "minioadmin"
  bucketName: "easychat"