server:
  port: 20020
  servlet:
    context-path: /auth
    session:
      tracking-modes: cookie

spring:
  application:
    name: gb-easychat-auth-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: 1dd53a7f-c79f-4620-ad6e-fade5bac680d
        cluster-name: shanghai
        group: easychat
  redis:
    host: localhost
    port: 6379
    password: 123456
    connect-timeout: 5000